name: Build Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Android APK ထုတ်ရန် Java လိုအပ်သောကြောင့် ထည့်သွင်းထားပါသည်
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flet
        run: pip install flet

      # ခွင့်ပြုချက်တောင်းပါက 'yes' ဟု အလိုလိုဖြေပေးရန် 'yes |' ကို ထည့်ထားပါသည်
      - name: Build APK
        run: yes | flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/**/*.apk
